In [1]:
import torch

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad  # The gradient is None by default

In [9]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [10]:
y.backward()
x.grad

tensor([ 0.,  8., 16., 24.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

In [11]:
x.grad.zero_()  # Reset the gradient

tensor([0., 0., 0., 0.])

In [12]:
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [13]:
y.backward()

In [ ]:
x.grad

tensor([1., 1., 1., 1.])

In [15]:
x.grad.zero_()
y = x * x
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [17]:
y.backward(gradient=torch.ones(len(y)))  # Faster: y.sum().backward()

In [18]:
x.grad

tensor([0., 2., 4., 6.])

In [19]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [20]:
u

tensor([0., 1., 4., 9.])

In [21]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [22]:
z

tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)

In [23]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [24]:
x.grad == y

tensor([True, True, True, True])

In [25]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [31]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [32]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d

tensor(-136739.7344, grad_fn=<MulBackward0>)

In [33]:
d.backward()

In [34]:
a

tensor(-0.3338, requires_grad=True)

In [35]:
a.grad == d / a

tensor(True)